version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - todo-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - API_PORT=3000
    restart: unless-stopped
    networks:
      - todo-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  todo-network:
    driver: bridge